.circleci/config.yml

fixes #17 
This adds a `release` job to CI which should trigger when a new tag is pushed. If the pushed tag matches the plugin version (as defined in the Makefile), then it will draft a new release.
This brings up a question about the dockerhub workflow. As it stands, a new image will be pushed (with the version tag) when a PR is merged to master. I don't think we want that, but we should have a discussion on what the right flow is.

setup automated release drafting from CI

---

.circleci/config.yml

Was missing the upload directory to the ghr command in the last PR. This adds it in as well as builds artifacts to upload.

add in missing path in ghr command and add build artifacts

---

Dockerfile

This PR does a few things:
- removes the GIT_TAG and GIT_COMMIT overrides which were preventing those values from being picked up
- removes MAINTAINER (deprecated) keyword in favor of labels
- uses `scratch` as the base image
- this requires CGO_ENABLED=0 to be set on build
The first two are just minor things, the last is sorta experimental work for minimizing/hardening the container. This setup appears to work just fine for the tests I've done. If no other problems show up, it may be good to apply this pattern elsewhere, if applicable.

Updates to the Dockerfile

---

.jenkins
Makefile

I use the `reuseNode: true` in other plugin CI pipelines, I'm pretty sure that was what fixed the vendoring issue...
also bump version in preparation for retrying the release

attempt to fix ci vendoring issue causing release failure

---

pkg/devices/led.go
pkg/devices/lock.go

- adds deviceState invocations to locks mirroring what was done in
`pkg/devices/led.go`
- :fingerscrossed:

Add individual state to Locks

---

Makefile
pkg/devices/airflow.go
pkg/devices/humidity.go
pkg/devices/led.go
pkg/devices/lock.go
pkg/devices/pressure.go
pkg/devices/temperature.go

- The emulator will mass-assign devices when using just the device.ID,
the current state of synse-v2-plugins require the guid in order to
ensure its using a serialized identifier for the device being
modified/read.
editors note: i'm not sure if the makefile is the only place i need to bump the version number, lmk if thats incorrect.

Update Lock/Led devices for device.GUID instead of device.ID

---

README.md
config/device/lock.yaml
pkg/devices/lock.go
pkg/outputs/outputs.go
pkg/plugin.go

https://github.com/vapor-ware/management-api/issues/67
**Note**: This would require a change to any emulator configurations which specify locks, following the pattern:
```diff
outputs:
-      - type: lock.state
+      - type: lock.status
```

change lock output from state to status

---

.jenkins

- Confirmed with tag 2.4.5-login.
https://build.vio.sh/blue/organizations/jenkins/vapor-ware%2Fsynse-emulator-plugin/detail/2.4.5-login/1/pipeline
closes #44

[pipeline] - docker login before gorel

---

Makefile
config/device/power.yaml
pkg/devices/power.go
pkg/outputs/outputs.go
pkg/plugin.go

I wasn't able to determine if the output container works. it crashes on startup for me but seems to work for erick.
Here's the addition to the power devices so we can support a model of the egauges deployed, which include cumulative KWH meters, and voltage meters.

[power] - Adds KWH and Voltage type devices.

---

Makefile
pkg/devices/common.go
pkg/devices/fan.go
pkg/devices/led.go

- fixes a bug where action checks could fall through if the value is unsupported, leading the write transaction to finish as OK since it returns nil.
- bumps to v3.0.0-alpha.5

fix bug where unsupported action leads to write success

---

.goreleaser.yml

This PR:
- fixes the goreleaser config import paths so build-time args can be set properly. this issue was introduced in the change from `dep` to `go mod` (dependencies not vendored in the same manner)
fixes #73

fix goreleaser config for build time arg paths

---

.goreleaser.yml
.jenkins

This PR:
- fixes a block indentation
- removes the GOVERSION env variable.. we need this for goreleaser, but I believe that env is set in the agent golang container (@lazypower correct me if I'm wrong here)
- replaces the tag match regex with the simpler `buildingTag` directive

various updates to CI config

---

.jenkins
Makefile

This PR:
- updates CI config to run goreleaser in debug mode. makes it easier to debug a failure if there ever is one.
- cleans up build flag pathing in makefile.

run goreleaser in debug mode in CI

---

go.mod
go.sum
pkg/devices/fan.go

This PR:
- updates and tidies deps
- changes the fan output from airflow to RPM
- augments the RPM output with min/max in the context
- adds a direction to the fan read output
This should help with testing autofan in a virtual chamber

add direction to fan return, add min/max in speed context

---

Makefile
docker-compose.yml
go.mod
go.sum

This PR:
- bumps the emulator version to `3.0.0-alpha.10`
- updates dependencies to use the latest SDK which includes some bugfixes
- updates compose file name
- updates compose file to enable metrics and expose the metrics port

update SDK version, rename and update compose file

---

config/device/carousel.yaml
pkg/actions.go
pkg/devices/carousel.go
pkg/outputs/outputs.go
pkg/plugin.go

This PR:
- adds the carousel device to the synse v3 branch. due to the changes from v2->v3, this could not just be merged/picked from master onto this branch.

port emulated carousel for v3 emulator

---

pkg/actions.go
pkg/devices/current.go
pkg/devices/frequency.go
pkg/plugin.go

This PR:
- adds "current" and "frequency" type devices to the emulator.
This was added to the master (synse v2) build in https://github.com/vapor-ware/synse-emulator-plugin/pull/57, but was not rolled up into the v3 work, until now.

add frequency and current devices

---

pkg/outputs/outputs.go

This PR:
- adds in a missing `Type` definition for custom emulator outputs. In v2, type/name were sorta the same; in v3 they are called out explicitly. The output types here were not updated completely to reflect that.

add missing type field to custom emulator outputs

---

config/device/airflow.yaml
config/device/carousel.yaml
config/device/fan.yaml
config/device/humidity.yaml
config/device/led.yaml
config/device/lock.yaml
config/device/power.yaml
config/device/pressure.yaml
config/device/temperature.yaml

This PR:
- fixes misconfiguration in device configs for v3, where the "metadata" key was replaced by "context"

fix device misconfiguration: key change for v3 config

---

.goreleaser.yml

This PR:
-  adds a number of commit prefixes to the list of those ignored when building a release changelog
Any suggestions for additional prefixes  are welcome (:

ci: filter changelong on standardized set of commit message prefixes

---

.dockerignore
Dockerfile.dev
Makefile
README.md
go.sum

This PR:
-  Adds a Dockerfile for building  development/debug images locally.
-  Updates the README with details about this image
Note that this image is not published via CI. It could be, but it seems unnecessary to  do that for every commit.
In a way, this PR is a proposal of what this image / process could look like, so feedback appreciated. Once this looks solid, I can work my way through other plugins and add the same to make building these kinds of images easier.

feat: add dockerfile for building dev/debug images
